docman/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from dropme import views as dropme_views
from rest_framework import routers as rest_routers

rest_router = rest_routers.DefaultRouter()
rest_router.register(r'users', dropme_views.UserViewSet)
rest_router.register(r'clipboards', dropme_views.ClipboardViewSet)
rest_router.register(r'documents', dropme_views.DocumentViewSet)

urlpatterns = [
    url(r'^accounts/profile/$', dropme_views.myprofile, name="my_profile"),
    url(r'^admin/', admin.site.urls),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^activity/', include('actstream.urls')),

    url(r'^$', dropme_views.homepage, name="homepage"),
    url(r'^dashboard$', dropme_views.dashboard, name="dashboard"),
    url(r'^u/(?P<username>[\w.-]+)/$', dropme_views.userprofile, name="user_profile"),
    url(r'clipboards/create/', dropme_views.create_clipboard, name="create_clipboard"),
    url(r'^item/preview_image/(?P<doc_id>[\d]+)/(?P<size>[\w]+)$', dropme_views.file_preview),
    url(r'^item/preview_image/(?P<doc_id>[\d]+)/(?P<size>[\w]+)/(?P<page>[\d]+)$', dropme_views.file_preview,
        name="preview_image"),

    url(r'^documents/raw/(?P<doc_id>[\w.-]+)/$', dropme_views.file_raw, name="file_raw"),
    url(r'(?P<token>[\w-]{9})/(?P<slug>[\w-]+)/$', dropme_views.show_clipboard, name="show_clipboard"),
    url(r'd/(?P<doc_id>[\d]+)$', dropme_views.show_document, name="show_document"),
    url(r'(?P<readonly_token>[\w-]{12})$', dropme_views.show_document, name="show_document_sharer"),

]

dropmefiles/urls.py
from django.conf.urls import patterns, url, include

from dropmefiles import views, api

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', api.UserViewSet)
router.register(r'clipboards', api.ClipboardViewSet)
router.register(r'items', api.ItemViewSet)


urlpatterns = patterns('',
    url(r'^$', views.index, name='home'),
    url(r'^test1$', views.test1, name='test1'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    
    url(r'^list/$', views.list_clipboards, name='list_clipboards'),
    url(r'^\@([-\w0-9._]*)/([-\w0-9._]+)/$', views.show_clipboard, name='show_clipboard'),
    url(r'^\@([-\w0-9._]*)/([-\w0-9._]+)/([-\w0-9._]+)$', views.show_item, name='show_item'),
    url(r'^raw/([-\w0-9._]*)/([-\w0-9._]+)/([-\w0-9._]+)$', views.show_raw_item, name='show_raw_item'),
    url(r'^\@([-\w0-9._]*)/$', views.show_user, name='show_user'),
    
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    
    
)

dropmefiles/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

from thewiki.models import User
from django.utils.encoding import python_2_unicode_compatible
import json

# Create your models here.

@python_2_unicode_compatible
class Clipboard(models.Model):
    STATE_PRIVATE = 1
    STATE_PROTECTED = 2
    STATE_PUBLIC = 3
    STATE_CHOICES = (
        (STATE_PRIVATE, 'Private'),
        (STATE_PROTECTED, 'Protected'),
        (STATE_PUBLIC, 'Public')
    )
    class Meta:
        managed = False
        db_table = "twiki_clipboard"
    cbid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=60)
    owner = models.ForeignKey("thewiki.User", db_column="owner", to_field="username")
    description = models.TextField()
    state = models.IntegerField(choices=STATE_CHOICES)
    viewmode = models.CharField(max_length=10)
    sortorder = models.CharField(max_length=10)
    temp = models.IntegerField()
    listable = models.IntegerField()
    indexed = models.IntegerField()
    invited_edit_all = models.IntegerField()
    invited_no_temp = models.IntegerField()
    comments = models.IntegerField()
    deleted = models.IntegerField()
    created = models.DateTimeField()
    lastmodified = models.DateTimeField()
    icon = models.CharField(max_length=90)
    
    def view_perm_of(self, user):
        if self.state == Clipboard.STATE_PRIVATE and user != self.owner:
            #if invited:
            #   return True
            return False
        else:
            return True
    
    def upload_perm_of(self, user):
        if self.state == Clipboard.STATE_PUBLIC:
            return True
        if self.owner == user:
            return True
        #if invited with write permission:
        #   return true
        return False
    
    
    def __str__(self):
        return self.name + " : " + self.description



@python_2_unicode_compatible
class Item(models.Model):
    class Meta:
        managed = False
        db_table = "twiki_clipitem"
    cid = models.AutoField(primary_key=True)
    clipboard = models.ForeignKey("Clipboard", db_column="cbid")
    
    title = models.CharField(max_length=80)
    filename = models.CharField(max_length=80)
    url_filename = models.CharField(max_length=80)
    server_filespec = models.CharField(max_length=180)
    
    private_flags = models.IntegerField()
    sort_index = models.IntegerField()
    
    created_by = models.CharField(max_length=25)
    created = models.DateTimeField()
    lastmodified_by = models.CharField(max_length=25)
    lastmodified = models.DateTimeField()
    
    filetype = models.CharField(max_length=20)
    subtype = models.CharField(max_length=20)
    filesize = models.IntegerField()
    
    deleted = models.IntegerField()
    properties = models.IntegerField()
    source_url = models.TextField()
    source_title = models.TextField()
    
    tags = models.CharField(max_length=100)
    categories = models.CharField(max_length=100)
    comment = models.TextField()
    
    uploader_ip = models.CharField(max_length=20)
    upload_via = models.IntegerField()
    
    def raw_url(self):
        return reverse("show_raw_item",args=( self.clipboard.owner_id, self.clipboard.name, self.url_filename))
        #return "http://u.dropme.de%s" % self.server_filespec
    
    def preview_url(self):
        return self.raw_url()
    
    def full_path(self):
       return settings.DROPME_STORE_DIRECTORY + self.server_filespec
    
    def read_file_contents(self):
        with open (self.full_path(), "r") as myfile:
            return myfile.read()
    
    def view_url(self):
        return reverse('show_item', args=(self.clipboard.owner_id, self.clipboard.name, self.url_filename))
    
    def __str__(self):
        return self.filename



@python_2_unicode_compatible
class Favorites(models.Model):
    class Meta:
        managed = False
        db_table = "twiki_clipfav"
    cfid = models.AutoField(primary_key=True)
    
    user = models.ForeignKey("thewiki.User", db_column="uid")
    clipboard = models.ForeignKey("Clipboard", db_column="cbid")
    alias = models.CharField(max_length=25)
    tag = models.CharField(max_length=25)
    color = models.CharField(max_length=6)
    
    def __str__(self):
        return self.clipboard.name



@python_2_unicode_compatible
class Events(models.Model):
    class Meta:
        managed = False
        db_table = "twiki_clipevent"
    ceid = models.AutoField(primary_key=True)
    
    user = models.ForeignKey("thewiki.User", db_column="actor", to_field="username")
    clipboard = models.ForeignKey("Clipboard", db_column="cbid")
    type = models.CharField(max_length=10)
    subtype = models.CharField(max_length=10)
    data = models.TextField()
    created = models.DateTimeField(db_column="ein_dat")
    
    def get_item(self):
        try:
            itemid = self.get_data()['cid']
            return Item.objects.get(cid=itemid)
        except (AttributeError, Item.DoesNotExist) as ex:
            print "get_item failed", ex
            return None
        
    
    def get_data(self):
        return json.loads(self.data)
    
    
    def __str__(self):
        return self.clipboard.name

    
    

dropmefiles/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.exceptions import PermissionDenied
from django.utils.safestring import mark_safe
from dropmefiles.models import Clipboard, Item, Favorites, Events
from thewiki.models import User, Userlink
from django.shortcuts import get_object_or_404

from pygments.lexers import guess_lexer_for_filename, get_lexer_by_name

from pygments import highlight
from pygments.formatters import HtmlFormatter


# Create your views here.
def index(request):
    events = None
    if request.member != None:
        contacts = Userlink.objects.contact_names(request.member)
        events = Events.objects.filter(user_id__in=contacts).order_by('-created')[:20]
    return render(request, "dropmefiles/testindex.html", {"events": events})

def list_clipboards(request):
    if request.session.get('member_id', None) != None:
        user = request.member
        #ser.objects.get(id=request.session['member_id'])
        
        list = Clipboard.objects.filter(owner=user.username)
        return render(request, "dropmefiles/clipboard_list.html", { "list": list })
    else:
        return render(request, "dropmefiles/not_logged_in.html")

def show_clipboard(request, owner, cbname):
    try:
        clipboard = Clipboard.objects.get(name=cbname, owner_id=owner)
        if not clipboard.view_perm_of(request.member):
            raise PermissionDenied("Forbidden to load private clipboard")
        cbitems = Item.objects.filter(clipboard=clipboard)
        return render(request, "dropmefiles/thumbview.html", { "clipboard": clipboard, "items": cbitems })
    except Clipboard.DoesNotExist:
        raise Http404("Clipboard not found")

def show_item(request, owner, cbname, filename):
    item = get_object_or_404(Item, clipboard__name=cbname, clipboard__owner_id=owner, url_filename=filename)
    if not item.clipboard.view_perm_of(request.member):
            raise PermissionDenied("Forbidden to load private clipboard")
    
    formatted = None
    if item.filetype == "text" or item.filetype == "code":
        code = item.read_file_contents()
        try:
            lexer = guess_lexer_for_filename(item.filename, code)
        except:
            lexer = get_lexer_by_name("php")
        htmlformatter = HtmlFormatter(linenos=True, cssclass="source")
        formatted = mark_safe(highlight(code, lexer, htmlformatter))
    
    return render(request, "dropmefiles/itemview.html", { "item": item, "formattedCode": formatted })

def show_user(request, username):
    user = get_object_or_404(User, username=username)
    clipboards = Clipboard.objects.filter(owner=user)
    if user != request.member:
        clipboards = clipboards.filter(state=Clipboard.STATE_PROTECTED)
    return render(request, "dropmefiles/userview.html", { "user": user, "clipboards": clipboards })

def show_raw_item(request, owner, cbname, filename):
    item = get_object_or_404(Item, clipboard__name=cbname, clipboard__owner_id=owner, url_filename=filename)
    if not item.clipboard.view_perm_of(request.member):
            raise PermissionDenied("Forbidden to load private clipboard")
    response = HttpResponse("Success")
    response["X-Accel-Redirect"] = "/protected_files" + item.server_filespec
    del response["Content-Type"]
    return response


def login(request):
    if request.POST:
        m = User.objects.get(username=request.POST['username'])
        if m.check_password(request.POST['password']):
            request.session['member_id'] = m.id
            #return HttpResponse("You're logged in.")
            return HttpResponseRedirect("/")
        else:
            return HttpResponse("Your username and password didn't match.")
    else:
        return render(request, "dropmefiles/login.html")

#...And this one logs a member out, according to login() above:

def logout(request):
    try:
        del request.session['member_id']
    except KeyError:
        pass
    return HttpResponse("You're logged out.")

# Create your views here.
def test1(request):
    return HttpResponse("<h2>test 1</h2>")

dropmefiles/templates/dropmefiles/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/dropmefiles/style.css" />
    <link rel="stylesheet" href="/static/dropmefiles/pygments.css" />
    <title>{% block title %}Dropme{% endblock %}</title>
</head>

<body>
    {% block body %}
    <div id="sidebar">
        {% block sidebar %}
        {% load templatehelpers %}
        <ul>
            <li><a {% url_active 'home' %}>Home</a></li>
            <li><a {% url_active 'list_clipboards' %}>List</a></li>
        </ul>
        {% endblock %}
        <br>
        {% if loginUser %}
        <ul>
            <li><a {% url_active 'show_user' loginUser.username %}><b>{{loginUser.fullname}}</b></a></li>
            <li><a href="/logout/">Logout</a></li>
        </ul>
        <br>
        <ul>
            {% for fav in favs %}
            <li><a {% url_active 'show_clipboard' fav.clipboard.owner.username fav.clipboard.name %}>{{fav.clipboard.name}}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <ul>
            <li><a href="/login/">Login</a></li>
        </ul>
        {% endif %}
        
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
    {% endblock %}
</body>
</html>

dropmefiles/templates/dropmefiles/clipboard_list.html
{% extends "dropmefiles/base.html" %}

{% block content %}
<table class="cblist">
    <tr><td>Filename</td><td>Status</td><td>Last Modified</td></tr>
    {% for item in list %}
    <tr>
      <td><a href="{% url 'show_clipboard' item.owner.username item.name %}">{{item.description}}</a></td>
      <td>{{item.get_state_display}}</td>
      <td>{{item.lastmodified}}</td></tr>
    {% endfor %}
</table>

{% endblock %}

dropmefiles/templates/dropmefiles/itemview.html
{% extends "dropmefiles/base.html" %}

{% block body %}
{% if item.filetype == "photo" %}
<div class="bigimg">
<a href="{{ item.raw_url }}">
<img src="{{ item.raw_url }}"></a>
    <div class="trick"></div>

</div>
{% elif formattedCode != None %}
<div class="codebox highlight">
        {{formattedCode}}
</div>
{% else %}
<a href="{{ item.raw_url }}">
<img src="http://home.max-weller.de/docs/img/win-icons/imageres_158-48.png">
</a>
{% endif %}

<div id="header">
    <div class="inner">
        <h1>
        {% if item.clipboard.owner != None %}
            <a href="{% url "show_user" item.clipboard.owner_id %}">{{ item.clipboard.owner.fullname }}</a> &#187;
        {% endif %}
        <a href="{% url 'show_clipboard' item.clipboard.owner_id item.clipboard.name %}">{{ item.clipboard.description }}</a>
        
        &#187;
        {{ item.filename }}</h1>
        <div>Hochgeladen am {{ item.created }}</div>
        <div>Dateityp {{ item.filetype }}/{{ item.subtype }}</div>
        
    </div>
</div>
<style>
#header { position: fixed; bottom: 0; left: 0; right: 0; background: rgba(22,22,22,0.8); color: #ddd; opacity: 0.6; }
#header a { color: #ddd; }
#header:hover { opacity: 1; }
#header:hover, #header:hover a { color: white; }
#header .inner { padding: 10px; }
#header .inner h1 { font-weight: normal; margin: 0; padding: 0; font-size: 18pt; }
.codebox { padding-bottom: 100px; }
.linenodiv { color: #aaa; padding: 0 10px 0 5px; }
a { text-decoration: none; background-color: #05183C; color: #ddd; padding: 0 4px; }
a:hover { background-color: #1451DF; color: #fff; }

.bigimg {
  font-size: 0;
  text-align: center; position: absolute; top: 0; left: 0;
  width: 100%;  /* Container's dimensions */
  height: 100%;
  background: #222;
}
img {
  display: inline-block;
  vertical-align: middle;
  max-height: 100%;
  max-width: 100%;
}
.trick {
  display: inline-block;
  vertical-align: middle;
  height: 100%;
}
</style>


{% endblock %}

dropmefiles/templates/dropmefiles/login.html
{% extends "dropmefiles/base.html" %}

{% block content %}
<form action="/login/" method="post">
    {% csrf_token %}

    Username: <input type="text" name="username"><br>
    Password: <input type="password" name="password"><br>
    
    <input type="submit">
    
    
</form>

{% endblock %}

dropmefiles/templates/dropmefiles/not_logged_in.html
{% extends "dropmefiles/base.html" %}

{% block content %}
You're not logged in.
<p><a href="/login/">Login</a></p>

{% endblock %}

dropmefiles/templates/dropmefiles/testindex.html
{% extends "dropmefiles/base.html" %}



{% block content %}
<h1>Hello, World</h1>

<ul class="events">
{% for event in events %}{% with item=event.get_item %}
<li>


{% if event.type == "ITEM" and item != None  %}
<a href="{{ item.view_url }}" class="imgbox">
{% if event.get_data.filetype == "photo" %}
<div class="image" style="background-image:url({{ item.raw_url }});"></div>

{% endif %}
</a>

<span> - {{ event.get_data.filename }}</span>
{% endif %}

<small style="color:#888;font-size:6pt;">&lt;&lt;{{ event.type }}.{{event.subtype }}.<a href="{% url 'show_clipboard' event.clipboard.owner_id event.clipboard.name %}">{{event.clipboard.name}}</a>>></small>
</li>    
{% endwith %}{% endfor %}
</ul>

{% endblock %}

dropmefiles/templates/dropmefiles/thumbview.html
{% extends "dropmefiles/base.html" %}


{% block content %}
<h1>
    {% if clipboard.owner != None %}
        <a href="{% url "show_user" clipboard.owner_id %}">{{ clipboard.owner.fullname }}</a> &#187;
    {% endif %}
    {{ clipboard.description }}</h1>

<ul class="events">
{% for item in items %}
<li>
<a href="{{ item.view_url }}" class="imgbox">
{% if item.filetype == "photo" %}
<div class="image" style="background-image:url({{ item.preview_url }});"></div>
{% else %}
<div class="image" style="background-size:auto;background-image:url(http://home.max-weller.de/docs/img/win-icons/imageres_158-48.png);"></div>
{% endif %}
</a>
<span>{{ item.filename }}</span>
</li>    
{% endfor %}
</ul>

{% endblock %}

dropmefiles/templates/dropmefiles/userview.html
{% extends "dropmefiles/base.html" %}

{% block content %}
<img src="https://teamwiki.de/profile/{{ user.username}}/image">
<h1>{{ user.fullname }}</h1>


<ul class="events">
{% for cb in clipboards %}
<li>
<a href="{% url 'show_clipboard' cb.owner_id cb.name %}" class="imgbox">
<div class="image" style="background-size:auto;background-image:url(http://home.max-weller.de/docs/img/win-icons/imageres_158-48.png);"></div>
</a>
<span>{{ cb.name }}</span>
</li>    
{% endfor %}
</ul>

{% endblock %}